fix(stdlib): parse_json improved accuracy float parsing #755
vectordotdev/vrl pull request #767
Opened 2024-03-26 20:43 UTC by drmason13

Fixed by activating a feature in serde_json, see https://github.com/serde-rs/json/issues/536

For anyone somehow relying on the innaccurate/faster parsing of floats, it's technically a breaking change.

2024-03-26 21:18 UTC, pront requested changes
Thank you @drmason13. I wonder if a better approach is to add a flag and preserve backwards compatibility. Also the accurate parser is much slower so we might not want to turn it on unconditionally.

2024-03-26 21:19 UTC, pront commented
Also cc @jszwedko

2024-03-26 21:22 UTC, jszwedko commented
Thanks @drmason13 ! A concern I have is that this apparently comes at 2x overhead cost:

https://github.com/serde-rs/json/blob/b1ebf3888ed728c66c69581ba8d9c4aa7483f486/Cargo.toml#L60-L67

It would be nice to make this an optional feature that could be enabled at runtime but given it is a compiler flag I'm not seeing a way to do that. I'd be curious to see if this shows up in our benchmarks in Vector. I opened a PR to see if it flags any difference:

https://github.com/vectordotdev/vector/pull/20185

2024-03-27 12:57 UTC, drmason13 commented
The performance implications are a valid concern, interested to see what the benchmarks show.

I think it would get complicated to have this be controlled by a flag. Would you need two versions of the serde_json dependency - one with the feature and one without? I'm not sure how to do this.

2024-03-27 14:34 UTC, jszwedko commented
Agreed, the impact on Vector seems fairly negligible, I think likely because I/O dominates the tests rather than the extra CPU spent on encoding/decoding floats.

I would like to see this be an optional feature in the VRL crate, though, that could be enabled by Vector so that other consumers of the VRL crate can decide whether to opt into it. Do you mind refactoring this PR to do that? See https://doc.rust-lang.org/cargo/reference/features.html#dependency-features for what this looks like.

2024-03-29 11:17 UTC, drmason13 commented
Open to suggestions for the feature name, I've gone with mirroring the serde_json feature name for clarity.

2024-04-01 14:09 UTC, pront approved these changes

2024-04-01 14:15 UTC, merged